
print('나머지 구하기 ')
print(1 % 6)
print(2 % 6)
print(3 % 6)
print(4 % 6)
print(5 % 6)
print('뒤에 있는 숫자가 앞에 있는 숫자보다 클 경우 나머지는 항상 앞에 있는 숫자임! ')
print()
print('같은 숫자를 나눈 나머지는 0')
print(6 % 6)
print()
print('뒤에 숫자보다 큰 숫자를 나누면 나머지는 뒤의 값+(앞의값-뒤의값)')
print(7 % 6)
print(8 % 6)
print(9 % 6)
print(1 % 7)

